MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000

  RELATION_ON: True

  RELATION:
    MAKE_PAIR_PROPOSAL_CNT: 128
    MAX_PROPOSAL_PAIR: 2048
    PHRASE_POOLED_SIZE: 8
    PHRASE_CLUSTER: True
    APPLY_REGRESSION: True
    USE_DETECTION_RESULT_FOR_RELATION: True
    FIXED_ROI_HEAD: True
    FIXED_RPN: True
    RELATION_CLASS: 51
    NEG_POS_PHRASE_PROP_RATE: 4
    SEPARATED_BACKBONE: True
    TOPK_TRIPLETS: (50, 100, )
    SAMPLE_DETECTION_BOX: False

  ROI_BOX_HEAD:
    NUM_CLASSES: 151
    FEATURE_EXTRACTOR: "ResNet50Conv5ROIFeatureExtractorFlatten"
    PREDICTOR: "FastRCNNPredictorFlatten"


DATASETS:
  TRAIN: ("vg_150_50_train" ,)
  TEST: ("vg_150_50_test_small" ,)


SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (21000, )
  CHECKPOINT_PERIOD: 3000
  START_SAVE_CHECKPOINT: 3000
  MAX_ITER: 50400
  IMS_PER_BATCH: 8
