MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "VGG16"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000

  BACKBONE:
    CONV_BODY: "VGG16"
    FREEZE_CONV_BODY_AT: 5

  RELATION_ON: False

  RELATION:
    MAKE_PAIR_PROPOSAL_CNT: 128
    MAX_PROPOSAL_PAIR: 2048
    PHRASE_POOLED_SIZE: 8
    PHRASE_CLUSTER: True
    APPLY_REGRESSION: True
    USE_DETECTION_RESULT_FOR_RELATION: True
    FIXED_ROI_HEAD: True
    FIXED_RPN: True
    RELATION_CLASS: 51
    NEG_POS_PHRASE_PROP_RATE: 4
    SEPARATED_BACKBONE: True
    TOPK_TRIPLETS: (50, 100, )
    SAMPLE_DETECTION_BOX: False

  ROI_BOX_HEAD:
    NUM_CLASSES: 151
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"  # work like a single feature layer FPN
    PREDICTOR: "FPNPredictor"


DATASETS:
  TRAIN: ("vg_150_50_train_fat" ,)
  TEST: ("vg_150_50_test_small" ,)


SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (90000, )
  CHECKPOINT_PERIOD: 3000
  START_SAVE_CHECKPOINT: 3000
  MAX_ITER: 200000
  IMS_PER_BATCH: 8
