MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
    NMS: 0.5
    DETECTIONS_PER_IMG: 128


  RELATION_ON: True

  RELATION:
    MAKE_PAIR_PROPOSAL_CNT: 128
    MAX_PROPOSAL_PAIR: 2048
    PHRASE_POOLED_SIZE: 8
    PHRASE_CLUSTER: True
    APPLY_REGRESSION: True
    USE_DETECTION_RESULT_FOR_RELATION: True
    FIXED_ROI_HEAD: True
    FIXED_RPN: True
    RELATION_CLASS: 51
    NEG_POS_PHRASE_PROP_RATE: 4
    SEPARATED_BACKBONE: True
    TOPK_TRIPLETS: (50, 100, )
    SAMPLE_DETECTION_BOX: False

    FEATURE_REFINE:
      MASSAGE_PASSING: 0
      MP_UNIT_OUTPUT_DIM: 128

  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 151


DATASETS:
#  TRAIN: ("vg_150_50_train_fat" ,)
  TRAIN: ("vg_150_50_train_small" ,)
#  TRAIN: ("vg_150_50_train" ,)
  TEST: ("vg_150_50_test_small" ,)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 2
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (100000, )
  CHECKPOINT_PERIOD: 5000
  START_SAVE_CHECKPOINT: 5000
  MAX_ITER: 200000
