MODEL:
  META_ARCHITECTURE: "GeneralizedRCNNDet"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
    NMS: 0.4
    DETECTIONS_PER_IMG: 100

  VG_ON: True
  RELATION_ON: False

  VG:
    FIXED_BACKBONE: True
    FIXED_RPN: True
    FIXED_ROI_HEAD: True
    FG_IOU_THRESHOLD: 0.5
    BG_IOU_THRESHOLD: 0.2
    VOCAB_FILE: "datasets/skip-thoughts/vocab.json"
    SKIP_THROUGH_DATA_DIR: "datasets/skip-thoughts"

  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 151


DATASETS:
  TRAIN: ("flickr_train" ,)
  TEST: ("flickr_val" ,)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 2
SOLVER:
  BASE_LR: 0.05
  WEIGHT_DECAY: 0.0001
  STEPS: (40000, )
  CHECKPOINT_PERIOD: 4000
  START_SAVE_CHECKPOINT: 4000
  MAX_ITER: 80000
